### ISSUE TITLE
Remove acronyms for example app code

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.gallery#13]
Now that `teal.gallery` is public, we should consider removing acronyms that might be cryptic or not meaningful to external audiences.

For examples
![image](https://user-images.githubusercontent.com/78242757/221730988-776881b8-7467-45c8-8eeb-801073a778b2.png)
![image](https://user-images.githubusercontent.com/78242757/221731060-43da7dfb-8698-4e54-9ee2-cbd89d1427aa.png)

Replacing SPA => Roche Pharma, Data Sciences
Replacing ED => Early-phase development

There might be others, so worthwhile doing a quick sweep of all example apps.

**Comment by pawelru** [comment]
Just did a quick search for the highlighted acronyms and it seems that they exists mostly in titles, footers and home page. I propose to extend the scope of the task and make these more consistent so that it would be clear that they are coming from the same source as opposed being completely independent and very much different to each other.
Please make a call what information needs to be provided (e.g. what's the value behind "SPA"?) and also where. As an example, I propose to put _main_ packages used (with GH refs) into the app footer plus reference to `teal.gallery` to report any issues / questions. Another example is app source code. I think it's a good idea and relatively easy to implement but it is only in few apps from what I can see now. 
These are just a few items that I identified but definitely there's more to do.

**Comment by lcd2yyz** [comment]
@vedhav Thanks for catching these!

> 1. `early-dev` - This is shiny app was brought to you by ED SPA. For more information please contact NEST SME team.

This should be addressed after making requested change for https://github.com/insightsengineering/teal.gallery/pull/58#issuecomment-1698383145

> 2\. `longitudinal` - Comment - BEGIN: SPA Input Required To Modify Values Below To Reflect Study Specifics & END: SPA Input Required

Let's change all "SPA" wording to "Analyst"
In addition, noticed objects `lead_spa_name` and `lead_spa_uid` in code, change to `lead_analyst_name/uid`
