### ISSUE TITLE
Syncing screen change in Teal Demo App page

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.gallery#54]
### Feature description

On https://insightsengineering.github.io/teal.gallery/demo.html webpage, demo apps appears in a grid with a clickable gif image. However, the speed at which the gif changes or move between tabs are different between panels, so for webpage viewers, it's very messy with various parts of the webpage seems to be flashing at varying speed.

Suggest to improve the coordination and sync the "screen movement" to some consistent interval across all apps. For example, switching tabs every 2 sec for all apps, and maybe avoid scrolling actions all together.

As we have quite a few presentations/workshops upcoming, please consider prioritizing this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
As I understand it, you need to start with a video before you can convert it to a GIF. This task implies that the creator would need to perform extensive editing to ensure that each action takes the same amount of time.

I'm not convinced that this is worth the effort. Personally, I prefer asynchronous sequences because they feel more realistic and human.

Is the primary issue related to the abundance of movements causing distractions? 
If that's the case, should we consider limiting the movements? For example, could GIFs only play when the mouse hovers over them?

**Comment by lcd2yyz** [comment]
@donyunardi Thanks for sharing your thoughts! 

> Is the primary issue related to the abundance of movements causing distractions?

Yes, for a typical desktop screensize, user will see 6 autoplayed videos all flashing at different rates, it feels a bit overwhelming.

> For example, could GIFs only play when the mouse hovers over them?

Great suggestion! I do like this approach!
